### ISSUE TITLE
Documentation hasn't added tags since v0.3.2

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiff/ChainRules.jl#243]
Self-explanatory title. @kanav99 do you remember what the fix to this was?

**Comment by kanav99** [comment]
Usually it's because of Github Actions, the GITHUB_TOKEN just sometimes doesn't work. Best fix would be to have a new Documenter Key, don't use GITHUB_KEY at all

**Comment by oxinabox** [comment]
ChainRules.jl doesn't actually have docs, got rid of them a while agai (I suspect in 0.3.2)
The ChainRules.jl does link in the readme just go to the [ChainRulesCore.jl docs.](https://www.juliadiff.org/ChainRulesCore.jl/stable/)
Because ChainRules.jl doesn't have any methods or types of its own.

The ChainRulesCore docs seem up to date and to have their tags.


We should workout how to remove
https://www.juliadiff.org/ChainRules.jl/latest/.
Possibly replacing it with a redirect.

**Comment by oxinabox** [comment]
I have now deleted it.
