### ISSUE TITLE
Missing rule for factorial

### ISSUE THREAD

**Issue by mzgubic** [JuliaDiff/ChainRules.jl#344]
Should be added using `@non_differentiable factorial(n::Integer)`

**Comment by oxinabox** [comment]
I considered for a bit that we could define it using the gamma function, tereating it as the embedding of an integer as a float.
But I think that is wrong, since if you perturb the input you will just get an error.
So it should be `@non_differentiable`
https://math.stackexchange.com/questions/300526/derivative-of-a-factorial
